FROM node:20-bookworm-slim AS runtime
WORKDIR /app

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000
ENV DATABASE_URL=file:./data/app.db
ENV BETTER_AUTH_URL=http://localhost:3000
ENV BETTER_AUTH_SECRET=e0k2Jhf7HrH75pV4YA6aYRQY0TlzeiJZ

COPY package*.json ./
RUN npm config set strict-ssl false \
	&& npm install --omit=dev --no-audit --no-fund \
	&& npm install --no-save --no-audit --no-fund @libsql/linux-x64-gnu \
	&& node -e "require('@libsql/linux-x64-gnu'); console.log('libsql linux binary loaded')"

COPY .output ./.output
COPY data ./data

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
